<?php

/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

namespace App\Http\Controllers\Api1;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Api1\ApiController;
use Illuminate\Http\Request;
use App\Services\PublicFunctionService;

class AdminGeneralSettingApi extends ApiController
{
     /**
     * @var Illuminate\Http\Request
     */
    protected $request;

     /**
     * @var App\Services\PublicFunctionService
     */
    protected $public_functions;

    /**
     * Constructor
     */
    public function __construct(Request $request, PublicFunctionService $public_functions)
    {
        $this->request = $request;
        $this->public_functions = $public_functions;
    }


    /**
     * Operation deCryptoOnline
     *
     * Decode hash online.
     *
     *
     * @return Http response
     */
    public function deCryptoOnline()
    {
        // check login
        $user = $this->requiredAuthUser();
        if (empty($user)) return response('token_invalid', 401);

        //path params validation
        $this->validate($this->request, [
            'data' => 'required',
            'key' => 'required'
        ]);
        $input = $this->request->all();
        return $this->public_functions->deCrypto($input['data'], $input['key']);
    }
}
