<?php

/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api1;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Api1\ApiController;
use Illuminate\Http\Request;
use App\Services\MembershipsService;

class GetMembershipsApi extends ApiController
{

    /**
     * @var Illuminate\Http\Request
     */
    protected $request;

    /**
     * @var App\Services\MembershipsService
     */
    protected $memberships; 

    /**
     * Constructor
     */
    public function __construct(Request $request, MembershipsService $memberships)
    {
        $this->request = $request;
        $this->memberships = $memberships;
    }

    /**
     * Operation getMembershipByMomo
     *
     * Get Membership By Momo.
     *
     * @param string $qrcode  (required)
     *
     * @return Http response
     */
    public function getMembershipByMomo($qrcode)
    {
        $token = $this->request->header('Token');
        $partner_code = $this->request->header('partnerCode');

        if(empty($token)) {  return ['status'=> 404, 'message'=> 'Mã token không tìm thấy', 'data' => []]; }
        if(empty($partner_code)) {  return ['status'=> 404, 'message'=> 'Mã partner không tìm thấy', 'data' => []]; }
        if(empty($qrcode)) {  return ['status'=> 404, 'message'=> 'Mã Qrcode không tìm thấy', 'data' => []]; }
        if(strlen($qrcode) == 0) {  return ['status'=> 404, 'message'=> 'Mã Qrcode không tìm thấy', 'data' => []]; }
        
        try {
            return $this->memberships->getMembershipByMomo($token, $partner_code, $qrcode);
        } catch (Exception $e) {
            return response('ok', 200);
        }
    }

    public function loginMembershipForApp() {

        $token = $this->request->header('Token');
        $partner_code = $this->request->header('partnerCode');
        $input = $this->request->all();

        if(empty($token))        {  return ['status'=> 404, 'message'=> 'Mã token không tìm thấy',   'data' => []]; }
        if(empty($partner_code)) {  return ['status'=> 404, 'message'=> 'Mã partner không tìm thấy', 'data' => []]; }

        // code ...
    }
}
