<?php

/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api1;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Api1\ApiController;
use Illuminate\Http\Request;
use App\Services\TopupsService;
use Log;

class TopupApi extends ApiController
{
    /**
     * @var Illuminate\Http\Request
     */
    protected $request;

    /**
     * @var App\Services\TopupsService
     */
    protected $topups;

    /**
     * Constructor
     */
    public function __construct(Request $request, TopupsService $topups)
    {
        $this->request = $request;
        $this->topups = $topups;
    }

    /**
     * Operation topupMembershipByMomo
     *
     * List of Memberships.
     *
     *
     * @return Http response
     */
    public function topupMembershipByMomo()
    {
        $token = $this->request->header('Token');
        $content_type = $this->request->header('Content-Type');
        $input = $this->request->all();

        Log::info('$$MOMO-request: token:'.$token);
        Log::info('$$MOMO-request: input:'.json_encode($input));

        if(empty($token)) {  return ['status'=> 404, 'message'=> 'Mã token không tìm thấy', 'data' => []]; }
        if(empty($content_type)) {  return ['status'=> 404, 'message'=> 'Content-Type không tìm thấy', 'data' => []]; }
        if($content_type != 'application/json') {  return ['status'=> 404, 'message'=> 'Content-Type phải định dạng application/json', 'data' => []]; }
        if(count($input) == 0) {  return ['status'=> 404, 'message'=> 'Không tim thấy tham số', 'data' => []]; }
        
        try {
            return $this->topups->updateTopupMomoMembership($token, $input);
        } catch (Exception $e) {
            return response('ok', 200);
        }
    }    
}
